# SafariBooks Configuration File
# This file contains default configuration settings for the SafariBooks scraper

# Authentication settings
auth:
  # Path to cookies file (relative to project root)
  cookies_file: "cookies.json"
  
  # O'Reilly URLs
  urls:
    base_url: "https://learning.oreilly.com"
    api_base_url: "https://api.oreilly.com"
    profile_url: "https://learning.oreilly.com/profile/"
    login_url: "https://www.oreilly.com/member/auth/login/"
    login_entry_url: "https://learning.oreilly.com/login/unified/?next=/home/"
  
  # Session validation settings
  session_validation:
    # Endpoint to test session validity (lightweight)
    test_endpoint: "/profile/"
    # Timeout for session validation requests (seconds)
    timeout: 10
    # Maximum retries for session validation
    max_retries: 3

# Download settings
download:
  # Default output directory
  output_dir: "Books"
  
  # Request settings
  request_timeout: 30
  max_retries: 3
  retry_delay: 1
  
  # User agent string
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"

# EPUB generation settings
epub:
  # Default EPUB version
  version: "2.0"
  
  # Kindle compatibility
  kindle_compatibility: false
  
  # CSS processing
  css_optimization: true
  
  # Cover image settings
  cover_image:
    max_width: 600
    max_height: 800
    quality: 85

# Logging settings
logging:
  level: "INFO"
  format: "[%(asctime)s] %(levelname)s: %(message)s"
  date_format: "%d/%b/%Y %H:%M:%S"
  file: "safaribooks.log"

